/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { GiftCard__factory } from "./GiftCard__factory";
<<<<<<< Updated upstream
export { GiftDAO__factory } from "./GiftDAO__factory";
=======
export { GiftCardDAO__factory } from "./GiftCardDAO__factory";
// export { GiftDAO__factory } from "./GiftDAO__factory";
>>>>>>> Stashed changes
export { GiftFactory__factory } from "./GiftFactory__factory";
export { GiftNetwork__factory } from "./GiftNetwork__factory";
