/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGiftCard } from "./IGiftCard";
export type { IGiftDAO } from "./IGiftDAO";
export type { IGiftNetwork } from "./IGiftNetwork";
