/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GiftCard } from "./GiftCard";
export type { GiftDAO } from "./GiftDAO";
export type { GiftFactory } from "./GiftFactory";
export type { GiftNetwork } from "./GiftNetwork";
