/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GiftCard } from "./GiftCard";
export type { GiftCardDAO } from "./GiftCardDAO";
export type { GiftFactory } from "./GiftFactory";
